// Dữ liệu mẫu cho các tỉnh thành
export const provinces = [
  {
    id: 1,
    name: "Hà Nội",
    slug: "ha-noi",
    imageUrl: "/images/provinces/ha-noi.jpg",
    attractionCount: 15,
    description: "Thủ đô ngàn năm văn hiến với nhiều di tích lịch sử và văn hóa đặc sắc.",
  },
  {
    id: 2,
    name: "Hồ Chí Minh",
    slug: "ho-chi-minh",
    imageUrl: "/images/provinces/ho-chi-minh.jpg",
    attractionCount: 12,
    description: "Thành phố năng động và hiện đại nhất Việt Nam với nhiều điểm tham quan hấp dẫn.",
  },
  {
    id: 3,
    name: "Đà Nẵng",
    slug: "da-nang",
    imageUrl: "/images/provinces/da-nang.jpg",
    attractionCount: 8,
    description: "Thành phố đáng sống với những bãi biển đẹp và nhiều điểm du lịch hấp dẫn.",
  },
  {
    id: 4,
    name: "Huế",
    slug: "hue",
    imageUrl: "/images/provinces/hue.jpg",
    attractionCount: 10,
    description: "Cố đô với nhiều di tích lịch sử và văn hóa đặc sắc.",
  },
  {
    id: 5,
    name: "Hội An",
    slug: "hoi-an",
    imageUrl: "/images/provinces/hoi-an.jpg",
    attractionCount: 6,
    description: "Phố cổ đẹp như tranh vẽ với kiến trúc cổ kính và văn hóa đặc trưng.",
  },
  {
    id: 6,
    name: "Nha Trang",
    slug: "nha-trang",
    imageUrl: "/images/provinces/nha-trang.jpg",
    attractionCount: 7,
    description: "Thành phố biển xinh đẹp với nhiều bãi biển và điểm du lịch hấp dẫn.",
  },
  {
    id: 7,
    name: "Đà Lạt",
    slug: "da-lat",
    imageUrl: "/images/provinces/da-lat.jpg",
    attractionCount: 9,
    description: "Thành phố ngàn hoa với khí hậu mát mẻ và cảnh quan thiên nhiên tuyệt đẹp.",
  },
  {
    id: 8,
    name: "Hạ Long",
    slug: "ha-long",
    imageUrl: "/images/provinces/ha-long.jpg",
    attractionCount: 10,
    description: "Nổi tiếng với vịnh Hạ Long - một trong những kỳ quan thiên nhiên của thế giới.",
  },
]

// Dữ liệu mẫu cho các địa điểm du lịch
export const attractions = [
  // Hà Nội
  {
    id: 1,
    provinceId: 1,
    name: "Hồ Hoàn Kiếm",
    slug: "ho-hoan-kiem",
    imageUrl: "/placeholder.svg?height=400&width=600",
    description:
      "Hồ Hoàn Kiếm, còn được gọi là Hồ Gươm, là một hồ nước ngọt tự nhiên nằm ở trung tâm thành phố Hà Nội.",
    address: "Quận Hoàn Kiếm, Hà Nội",
    openingHours: "Mở cửa 24/7",
    ticketPrice: "Miễn phí",
    rating: 4.7,
    coordinates: { lat: 21.0285, lng: 105.8542 },
  },
  {
    id: 2,
    provinceId: 1,
    name: "Văn Miếu - Quốc Tử Giám",
    slug: "van-mieu-quoc-tu-giam",
    imageUrl: "/placeholder.svg?height=400&width=600",
    description:
      "Văn Miếu - Quốc Tử Giám là quần thể di tích đa dạng gồm Văn Miếu, nơi thờ Khổng Tử và Quốc Tử Giám, trường đại học đầu tiên của Việt Nam.",
    address: "58 Quốc Tử Giám, Đống Đa, Hà Nội",
    openingHours: "8:00 - 18:00",
    ticketPrice: "30.000 VNĐ",
    rating: 4.6,
    coordinates: { lat: 21.0293, lng: 105.8354 },
  },
  {
    id: 3,
    provinceId: 1,
    name: "Hoàng Thành Thăng Long",
    slug: "hoang-thanh-thang-long",
    imageUrl: "/placeholder.svg?height=400&width=600",
    description:
      "Hoàng thành Thăng Long là quần thể di tích gắn liền với lịch sử Thăng Long - Hà Nội, được UNESCO công nhận là Di sản văn hóa thế giới.",
    address: "19C Hoàng Diệu, Ba Đình, Hà Nội",
    openingHours: "8:00 - 17:00",
    ticketPrice: "40.000 VNĐ",
    rating: 4.5,
    coordinates: { lat: 21.0379, lng: 105.8414 },
  },

  // Hồ Chí Minh
  {
    id: 4,
    provinceId: 2,
    name: "Nhà thờ Đức Bà",
    slug: "nha-tho-duc-ba",
    imageUrl: "/placeholder.svg?height=400&width=600",
    description: "Nhà thờ Đức Bà là một công trình kiến trúc Gothic nổi tiếng tại trung tâm Thành phố Hồ Chí Minh.",
    address: "Công xã Paris, Bến Nghé, Quận 1, TP.HCM",
    openingHours: "8:00 - 17:00",
    ticketPrice: "Miễn phí",
    rating: 4.6,
    coordinates: { lat: 10.7798, lng: 106.699 },
  },
  {
    id: 5,
    provinceId: 2,
    name: "Bảo tàng Chứng tích Chiến tranh",
    slug: "bao-tang-chung-tich-chien-tranh",
    imageUrl: "/placeholder.svg?height=400&width=600",
    description:
      "Bảo tàng Chứng tích Chiến tranh là một bảo tàng về lịch sử chiến tranh Việt Nam tại Thành phố Hồ Chí Minh.",
    address: "28 Võ Văn Tần, Phường 6, Quận 3, TP.HCM",
    openingHours: "7:30 - 18:00",
    ticketPrice: "40.000 VNĐ",
    rating: 4.7,
    coordinates: { lat: 10.7798, lng: 106.6921 },
  },

  // Đà Nẵng
  {
    id: 6,
    provinceId: 3,
    name: "Bà Nà Hills",
    slug: "ba-na-hills",
    imageUrl: "/placeholder.svg?height=400&width=600",
    description: "Bà Nà Hills là khu du lịch nghỉ dưỡng nổi tiếng với Cầu Vàng và nhiều công trình kiến trúc độc đáo.",
    address: "Hoà Ninh, Hoà Vang, Đà Nẵng",
    openingHours: "7:00 - 22:00",
    ticketPrice: "750.000 VNĐ",
    rating: 4.8,
    coordinates: { lat: 15.9977, lng: 107.9886 },
  },
  {
    id: 7,
    provinceId: 3,
    name: "Bãi biển Mỹ Khê",
    slug: "bai-bien-my-khe",
    imageUrl: "/placeholder.svg?height=400&width=600",
    description: "Bãi biển Mỹ Khê được tạp chí Forbes bình chọn là một trong những bãi biển quyến rũ nhất hành tinh.",
    address: "Phường Phước Mỹ, Quận Sơn Trà, Đà Nẵng",
    openingHours: "Mở cửa 24/7",
    ticketPrice: "Miễn phí",
    rating: 4.7,
    coordinates: { lat: 16.0544, lng: 108.2478 },
  },

  // Hạ Long
  {
    id: 8,
    provinceId: 8,
    name: "Vịnh Hạ Long",
    slug: "vinh-ha-long",
    imageUrl: "/images/attractions/vinh-ha-long.jpg",
    description: "Vịnh Hạ Long là một trong những kỳ quan thiên nhiên của thế giới, với hàng nghìn đảo đá vôi và hang động tuyệt đẹp.",
    address: "Vịnh Hạ Long, Thành phố Hạ Long, Quảng Ninh",
    openingHours: "Mở cửa 24/7",
    ticketPrice: "290.000 VNĐ",
    rating: 4.9,
    coordinates: { lat: 20.9101, lng: 107.1839 },
  },
  {
    id: 9,
    provinceId: 8,
    name: "Hang Sửng Sốt",
    slug: "hang-sung-sot",
    imageUrl: "/images/attractions/hang-sung-sot.jpg",
    description: "Hang Sửng Sốt là một trong những hang động đẹp nhất vịnh Hạ Long, với hệ thống nhũ đá và măng đá độc đáo.",
    address: "Đảo Bồ Hòn, Vịnh Hạ Long, Quảng Ninh",
    openingHours: "8:00 - 17:00",
    ticketPrice: "Đã bao gồm trong vé tham quan vịnh",
    rating: 4.7,
    coordinates: { lat: 20.9022, lng: 107.1917 },
  },
  {
    id: 10,
    provinceId: 8,
    name: "Đảo Ti Tốp",
    slug: "dao-ti-top",
    imageUrl: "/images/attractions/dao-ti-top.jpg",
    description: "Đảo Ti Tốp nổi tiếng với bãi tắm đẹp và điểm ngắm cảnh toàn cảnh vịnh Hạ Long từ trên cao.",
    address: "Đảo Ti Tốp, Vịnh Hạ Long, Quảng Ninh",
    openingHours: "8:00 - 17:00",
    ticketPrice: "Đã bao gồm trong vé tham quan vịnh",
    rating: 4.6,
    coordinates: { lat: 20.9083, lng: 107.1889 },
  },

  // Huế
  {
    id: 11,
    provinceId: 4,
    name: "Đại Nội Huế",
    slug: "dai-noi-hue",
    imageUrl: "/images/attractions/dai-noi-hue.jpg",
    description: "Đại Nội Huế là quần thể di tích cố đô Huế, được UNESCO công nhận là Di sản văn hóa thế giới.",
    address: "23 Tháng 8, Phường Thuận Thành, Thành phố Huế",
    openingHours: "7:00 - 17:30",
    ticketPrice: "150.000 VNĐ",
    rating: 4.8,
    coordinates: { lat: 16.4706, lng: 107.5776 },
  },
  {
    id: 12,
    provinceId: 4,
    name: "Lăng Tự Đức",
    slug: "lang-tu-duc",
    imageUrl: "/images/attractions/lang-tu-duc.jpg",
    description: "Lăng Tự Đức là một trong những công trình kiến trúc đẹp nhất của triều Nguyễn, nằm trong khung cảnh thiên nhiên thơ mộng.",
    address: "Thôn Thượng Ba, Phường Thủy Xuân, Thành phố Huế",
    openingHours: "7:00 - 17:30",
    ticketPrice: "100.000 VNĐ",
    rating: 4.7,
    coordinates: { lat: 16.4324, lng: 107.5657 },
  },
  {
    id: 13,
    provinceId: 4,
    name: "Chùa Thiên Mụ",
    slug: "chua-thien-mu",
    imageUrl: "/images/attractions/chua-thien-mu.jpg",
    description: "Chùa Thiên Mụ là ngôi chùa cổ nhất ở Huế, nằm bên dòng sông Hương thơ mộng.",
    address: "Đường Nguyễn Phúc Nguyên, Phường Kim Long, Thành phố Huế",
    openingHours: "8:00 - 18:00",
    ticketPrice: "Miễn phí",
    rating: 4.6,
    coordinates: { lat: 16.4564, lng: 107.5456 },
  },

  // Hội An
  {
    id: 14,
    provinceId: 5,
    name: "Phố cổ Hội An",
    slug: "pho-co-hoi-an",
    imageUrl: "/images/attractions/pho-co-hoi-an.jpg",
    description: "Phố cổ Hội An là một trong những di sản văn hóa thế giới, với kiến trúc cổ kính và nét đẹp truyền thống.",
    address: "Phố cổ Hội An, Thành phố Hội An, Quảng Nam",
    openingHours: "Mở cửa 24/7",
    ticketPrice: "120.000 VNĐ",
    rating: 4.9,
    coordinates: { lat: 15.8801, lng: 108.3380 },
  },
  {
    id: 15,
    provinceId: 5,
    name: "Chùa Cầu",
    slug: "chua-cau",
    imageUrl: "/images/attractions/chua-cau.jpg",
    description: "Chùa Cầu là biểu tượng của Hội An, một công trình kiến trúc độc đáo kết hợp giữa chùa và cầu.",
    address: "Nguyễn Thị Minh Khai, Phường Minh An, Hội An",
    openingHours: "8:00 - 21:00",
    ticketPrice: "Đã bao gồm trong vé tham quan phố cổ",
    rating: 4.8,
    coordinates: { lat: 15.8772, lng: 108.3267 },
  },
  {
    id: 16,
    provinceId: 5,
    name: "Bãi biển An Bàng",
    slug: "bai-bien-an-bang",
    imageUrl: "/images/attractions/bai-bien-an-bang.jpg",
    description: "Bãi biển An Bàng là một trong những bãi biển đẹp nhất Hội An, với bãi cát trắng và nước biển trong xanh.",
    address: "Đường An Bàng, Cẩm An, Hội An",
    openingHours: "Mở cửa 24/7",
    ticketPrice: "Miễn phí",
    rating: 4.7,
    coordinates: { lat: 15.8889, lng: 108.3267 },
  },

  // Nha Trang
  {
    id: 17,
    provinceId: 6,
    name: "Vinpearl Land",
    slug: "vinpearl-land",
    imageUrl: "/images/attractions/vinpearl-land.jpg",
    description: "Vinpearl Land là khu vui chơi giải trí lớn nhất Nha Trang, với công viên nước, thủy cung và nhiều trò chơi hấp dẫn.",
    address: "Đảo Hòn Tre, Vịnh Nha Trang",
    openingHours: "8:30 - 21:00",
    ticketPrice: "880.000 VNĐ",
    rating: 4.8,
    coordinates: { lat: 12.1954, lng: 109.2965 },
  },
  {
    id: 18,
    provinceId: 6,
    name: "Tháp Bà Ponagar",
    slug: "thap-ba-ponagar",
    imageUrl: "/images/attractions/thap-ba-ponagar.jpg",
    description: "Tháp Bà Ponagar là quần thể kiến trúc Chăm Pa cổ, nằm trên đồi Cù Lao, bên bờ sông Cái.",
    address: "2 Tháng 4, Vĩnh Phước, Nha Trang",
    openingHours: "8:00 - 18:00",
    ticketPrice: "22.000 VNĐ",
    rating: 4.6,
    coordinates: { lat: 12.2653, lng: 109.1955 },
  },
  {
    id: 19,
    provinceId: 6,
    name: "Bãi biển Nha Trang",
    slug: "bai-bien-nha-trang",
    imageUrl: "/images/attractions/bai-bien-nha-trang.jpg",
    description: "Bãi biển Nha Trang là một trong những bãi biển đẹp nhất Việt Nam, với bãi cát trắng dài và nước biển trong xanh.",
    address: "Trần Phú, Lộc Thọ, Nha Trang",
    openingHours: "Mở cửa 24/7",
    ticketPrice: "Miễn phí",
    rating: 4.7,
    coordinates: { lat: 12.2388, lng: 109.1967 },
  },

  // Đà Lạt
  {
    id: 20,
    provinceId: 7,
    name: "Hồ Xuân Hương",
    slug: "ho-xuan-huong",
    imageUrl: "/images/attractions/ho-xuan-huong.jpg",
    description: "Hồ Xuân Hương là trái tim của Đà Lạt, nơi du khách có thể thư giãn và ngắm cảnh thành phố ngàn hoa.",
    address: "Phường 1, Thành phố Đà Lạt",
    openingHours: "Mở cửa 24/7",
    ticketPrice: "Miễn phí",
    rating: 4.7,
    coordinates: { lat: 11.9404, lng: 108.4373 },
  },
  {
    id: 21,
    provinceId: 7,
    name: "Thung lũng Tình Yêu",
    slug: "thung-lung-tinh-yeu",
    imageUrl: "/images/attractions/thung-lung-tinh-yeu.jpg",
    description: "Thung lũng Tình Yêu là điểm đến lãng mạn với hồ nước, đồi thông và vườn hoa đẹp mắt.",
    address: "Phường 8, Thành phố Đà Lạt",
    openingHours: "7:00 - 17:00",
    ticketPrice: "60.000 VNĐ",
    rating: 4.6,
    coordinates: { lat: 11.9306, lng: 108.4500 },
  },
  {
    id: 22,
    provinceId: 7,
    name: "Dinh Bảo Đại",
    slug: "dinh-bao-dai",
    imageUrl: "/images/attractions/dinh-bao-dai.jpg",
    description: "Dinh Bảo Đại là nơi ở của vua Bảo Đại, vị vua cuối cùng của triều Nguyễn, với kiến trúc Pháp cổ điển.",
    address: "1 Triệu Việt Vương, Phường 4, Đà Lạt",
    openingHours: "7:00 - 17:00",
    ticketPrice: "40.000 VNĐ",
    rating: 4.5,
    coordinates: { lat: 11.9404, lng: 108.4373 },
  },

  // Thêm địa điểm cho Hà Nội
  {
    id: 31,
    provinceId: 1,
    name: "Phố đi bộ Hồ Gươm",
    slug: "pho-di-bo-ho-guom",
    imageUrl: "/images/attractions/pho-di-bo-ho-guom.jpg",
    description: "Không gian văn hóa, giải trí sôi động vào cuối tuần với nhiều hoạt động nghệ thuật đường phố.",
    address: "Phố Đinh Tiên Hoàng, Hoàn Kiếm, Hà Nội",
    openingHours: "19:00 - 24:00 (T6-CN)",
    ticketPrice: "Miễn phí",
    rating: 4.6,
    coordinates: { lat: 21.0286, lng: 105.8525 }
  },
  {
    id: 32,
    provinceId: 1,
    name: "Phố cổ 36 phố phường",
    slug: "pho-co-36-pho-phuong",
    imageUrl: "/images/attractions/pho-co-ha-noi.jpg",
    description: "Khu phố cổ với kiến trúc đặc trưng và nhiều cửa hàng truyền thống.",
    address: "Quận Hoàn Kiếm, Hà Nội",
    openingHours: "Cả ngày",
    ticketPrice: "Miễn phí",
    rating: 4.7,
    coordinates: { lat: 21.0338, lng: 105.8500 }
  },
  {
    id: 33,
    provinceId: 1,
    name: "Văn Miếu - Quốc Tử Giám",
    slug: "van-mieu-quoc-tu-giam",
    imageUrl: "/images/attractions/van-mieu.jpg",
    description: "Trường đại học đầu tiên của Việt Nam, di tích lịch sử văn hóa quan trọng.",
    address: "58 Quốc Tử Giám, Đống Đa, Hà Nội",
    openingHours: "8:00 - 18:00",
    ticketPrice: "30.000 VNĐ",
    rating: 4.8,
    coordinates: { lat: 21.0293, lng: 105.8359 }
  },

  // Thêm địa điểm cho Hồ Chí Minh
  {
    id: 34,
    provinceId: 2,
    name: "Phố đi bộ Nguyễn Huệ",
    slug: "pho-di-bo-nguyen-hue",
    imageUrl: "/images/attractions/pho-di-bo-nguyen-hue.jpg",
    description: "Không gian công cộng sôi động với nhiều hoạt động văn hóa, giải trí.",
    address: "Đường Nguyễn Huệ, Quận 1, TP.HCM",
    openingHours: "18:00 - 22:00",
    ticketPrice: "Miễn phí",
    rating: 4.5,
    coordinates: { lat: 10.7731, lng: 106.7029 }
  },
  {
    id: 35,
    provinceId: 2,
    name: "Chợ Bến Thành",
    slug: "cho-ben-thanh",
    imageUrl: "/images/attractions/cho-ben-thanh.jpg",
    description: "Khu chợ truyền thống nổi tiếng với nhiều mặt hàng đa dạng.",
    address: "Đường Lê Lợi, Quận 1, TP.HCM",
    openingHours: "6:00 - 24:00",
    ticketPrice: "Miễn phí",
    rating: 4.4,
    coordinates: { lat: 10.7724, lng: 106.6980 }
  },
  {
    id: 36,
    provinceId: 2,
    name: "Bảo tàng Chứng tích Chiến tranh",
    slug: "bao-tang-chung-tich-chien-tranh",
    imageUrl: "/images/attractions/bao-tang-chung-tich-chien-tranh.jpg",
    description: "Bảo tàng trưng bày về lịch sử chiến tranh Việt Nam.",
    address: "28 Võ Văn Tần, Quận 3, TP.HCM",
    openingHours: "7:30 - 18:00",
    ticketPrice: "40.000 VNĐ",
    rating: 4.7,
    coordinates: { lat: 10.7798, lng: 106.6925 }
  },

  // Thêm địa điểm cho Đà Nẵng
  {
    id: 37,
    provinceId: 3,
    name: "Cầu Rồng",
    slug: "cau-rong",
    imageUrl: "/images/attractions/cau-rong.jpg",
    description: "Cây cầu biểu tượng của Đà Nẵng với hình dáng con rồng phun lửa và nước.",
    address: "Phường An Hải Tây, Quận Sơn Trà, Đà Nẵng",
    openingHours: "Cả ngày",
    ticketPrice: "Miễn phí",
    rating: 4.8,
    coordinates: { lat: 16.0611, lng: 108.2272 }
  },
  {
    id: 38,
    provinceId: 3,
    name: "Asia Park",
    slug: "asia-park",
    imageUrl: "/images/attractions/asia-park.jpg",
    description: "Công viên giải trí hiện đại với nhiều trò chơi hấp dẫn.",
    address: "1 Phan Đăng Lưu, Hải Châu, Đà Nẵng",
    openingHours: "15:00 - 22:00",
    ticketPrice: "200.000 VNĐ",
    rating: 4.5,
    coordinates: { lat: 16.0469, lng: 108.2237 }
  },
  {
    id: 39,
    provinceId: 3,
    name: "Làng Bích Họa Tam Thanh",
    slug: "lang-bich-hoa-tam-thanh",
    imageUrl: "/images/attractions/lang-bich-hoa-tam-thanh.jpg",
    description: "Làng quê với những bức tranh tường nghệ thuật độc đáo.",
    address: "Tam Thanh, Tam Kỳ, Quảng Nam",
    openingHours: "Cả ngày",
    ticketPrice: "Miễn phí",
    rating: 4.6,
    coordinates: { lat: 15.5738, lng: 108.4837 }
  },

  // Thêm địa điểm cho Hạ Long
  {
    id: 40,
    provinceId: 8,
    name: "Bãi Cháy",
    slug: "bai-chay",
    imageUrl: "/images/attractions/bai-chay.jpg",
    description: "Bãi biển nhân tạo đẹp với nhiều dịch vụ giải trí.",
    address: "Phường Bãi Cháy, TP. Hạ Long, Quảng Ninh",
    openingHours: "Cả ngày",
    ticketPrice: "Miễn phí",
    rating: 4.4,
    coordinates: { lat: 20.9584, lng: 107.0720 }
  },
  {
    id: 41,
    provinceId: 8,
    name: "Công viên Sun World",
    slug: "cong-vien-sun-world-ha-long",
    imageUrl: "/images/attractions/sun-world-ha-long.jpg",
    description: "Khu vui chơi giải trí hiện đại với nhiều trò chơi thú vị.",
    address: "Bãi Cháy, TP. Hạ Long, Quảng Ninh",
    openingHours: "8:00 - 21:30",
    ticketPrice: "700.000 VNĐ",
    rating: 4.6,
    coordinates: { lat: 20.9589, lng: 107.0759 }
  },
  {
    id: 42,
    provinceId: 8,
    name: "Bảo tàng Quảng Ninh",
    slug: "bao-tang-quang-ninh",
    imageUrl: "/images/attractions/bao-tang-quang-ninh.jpg",
    description: "Bảo tàng hiện đại giới thiệu về lịch sử và văn hóa Quảng Ninh.",
    address: "Trần Quốc Nghiễn, TP. Hạ Long, Quảng Ninh",
    openingHours: "8:00 - 17:00",
    ticketPrice: "40.000 VNĐ",
    rating: 4.5,
    coordinates: { lat: 20.9508, lng: 107.0997 }
  }
]

// Dữ liệu mẫu cho người dùng
export const users = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    email: "nguyenvana@example.com",
    password: "password123", // Trong thực tế, mật khẩu phải được mã hóa
    savedAttractions: [1, 3, 6],
  },
  {
    id: 2,
    name: "Trần Thị B",
    email: "tranthib@example.com",
    password: "password456",
    savedAttractions: [2, 4, 7],
  },
]
